CREATE TABLE driver(
    driverid VARCHAR2(10) CONSTRAINT DRIVERID_FORMAT CHECK (DRIVERID LIKE 'DR%') CONSTRAINT DRIVERID_PK PRIMARY KEY,
    LICENSENUMBER NUMBER CONSTRAINT UNIQUE_LN UNIQUE,
    LICENSEEXPIRY DATE,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR(20),
    STREET VARCHAR(20),
    CITY VARCHAR(20)
);

CREATE TABLE VEHICLE(
    VEHICLEID VARCHAR(10) CONSTRAINT VEHICLEID_FORMAT CHECK (VEHICLEID LIKE 'VH%') CONSTRAINT VEHICLEID_PK PRIMARY KEY,
    MODEL VARCHAR(10),
    MILEAGE NUMBER(10),
    REGYEAR VARCHAR(4) CONSTRAINT YEAR_FORMAT CHECK (
        REGYEAR LIKE '19__'
        OR REGYEAR LIKE '2___'
    ),
);

CREATE TABLE TRIP(
    TRIPID VARCHAR2(10) CONSTRAINT TRIPID_PK PRIMARY KEY CONSTRIANT TRIPID_FORMAT CHECK (TRIPID LIKE 'TR%'),
    STARTDATE DATE,
    ENDDATE DATE,
    STARTLOCATION VARCHAR2(20),
    DESTINATION VARCHAR(20),
    DISTANCE NUMBER(20),
    PASSENGERCOUNT NUMBER(10),
    CONSTRAINT END_GREATER_START CHECK (ENDDATE >= STARTDATE);

);

CREATE TABLE COST(
    COSTID VARCHAR2(10) CONSTRAINT COSTID_FORMAT CHECK (COSTID LIKE 'CS%') CONSTRAINT COSTID_PK PRIMARY KEY,
    TRIPID VARCHAR2(10) CONSTRAINT TRIPID_FK REFERENCES TRIP,
    FUELCOST NUMBER(20) CONSTRAINT GREATERTHAN0 CHECK (FUELCOST > 0),
    TOTALCOST NUMBER(20),
    CONSTRAINT TC_GREATER_FC CHECK (TOTALCOST > FUELCOST)
);

CREATE TABLE VEHICLE_INVOLVED(
    TRIPID VARCHAR2(10) CONSTRAINT TRIPID_FK REFERENCES TRIP,
    VEHICLEID VARCHAR2(10) CONSTRAINT VEHICLEID_FK REFERENCES VEHICLE,
    CONSTRAINT VI_PK PRIMARY KEY (TRIPID, VEHICLEID)
);

CREATE TABLE DRIVER_INVOLVED(
    TRIPID VARCHAR2(10) CONSTRAINT TRIPID_FK REFERENCES TRIP,
    DRIVERID VARCHAR2(10) CONSTRAINT DRIVERID_FK REFERENCES DRIVER,
    CONSTRAINT DI_PK PRIMARY KEY (TRIPID, DRIVERID)
);

CREATE TABLE DRIVER_PHONE(
   
     DRIVERID VARCHAR2(10)  CONSTRAINT DRIVERID_FK REFERENCES DRIVER,
     PHONE VARCHAR2(10) CONSTRAINT TEN_DIGIT CHECK (PHONE LIKE '__________'),
     CONSTRAINT DI_PK PRIMARY KEY (PHONE,DRIVERID)
);
